AWSTemplateFormatVersion: "2010-09-09"
Description: "Main stack linking VPC, Subnets, and EC2 using nested stacks"

Parameters:
  TemplateBucket:
    Type: String
    Description: S3 bucket name containing templates
  Env:
    Type: String
    Description: Environment
  DeployDir:
    Type: String
    Description: Deployment directory

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/${DeployDir}/vpc.yml
      Parameters:
        VPCCidrBlock: 10.127.0.0/20
        Environment: !Ref Env
        TagName: nms-me-south-1
        TagRegion: me-south-1
        ExportName: vpc-nsg-${Env}-me-south-1

  PublicSubnetStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/${DeployDir}/subnet.yml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        ExportName: sub-pub-nsg-${Env}-me-south-1a
        AvailabilityZone: me-south-1a
        Environment: !Ref Env
        TagRegion: me-south-1a
        CidrBlock: 10.127.0.0/24
        IsPubIp: true

  PrivateSubnetStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/${DeployDir}/subnet.yml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        ExportName: sub-pvt-nsg-${Env}-me-south-1a
        AvailabilityZone: me-south-1a
        Environment: !Ref Env
        TagRegion: me-south-1a
        CidrBlock: 10.127.1.0/24
        IsPubIp: false

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: PublicSubnetStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/${DeployDir}/ec2.yml
      Parameters:
        SubnetId: !GetAtt PublicSubnetStack.Outputs.PubOrPvtSubnetId
        SubnetType: public
        Environment: !Ref Env
        TagRegion: me-south-1a
        Size: t3.micro
        ExportName: ec2-sub-pvt-nsg-${Env}-me-south-1a

Outputs:
  VpcId:
    Description: Created VPC ID
    Value: !GetAtt VPCStack.Outputs.VpcId

  PublicSubnetId:
    Description: Public Subnet ID
    Value: !GetAtt PublicSubnetStack.Outputs.PubOrPvtSubnetId

  PrivateSubnetId:
    Description: Private Subnet ID
    Value: !GetAtt PrivateSubnetStack.Outputs.PubOrPvtSubnetId
