AWSTemplateFormatVersion: '2010-09-09'
Description: Route tables for public and private subnets

Parameters:
  VpcId:
    Type: String
  PublicSubnetId:
    Type: String
  PrivateSubnetIds:
    Type: CommaDelimitedList

Resources:
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: rt-vpc-nms-dev-me-south-1a
        - Key: Env
          Value: dev
        - Key: Region
          Value: me-south-1a
        - Key: Apps
          Value: NMS
        - Key: Owner
          Value: Oreta Dev Team
        - Key: ITSM
          Value: ITSM-1234
        - Key: CostCentre
          Value: CC-1234

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: PublicRouteTable
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: 
        Fn::ImportValue: MyVPCID

  PublicSubnetRouteTableAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetId
      RouteTableId: !Ref PublicRouteTable

Outputs:
  PublicRouteTableId:
    Value: !Ref PublicRouteTable
