AWSTemplateFormatVersion: '2010-09-09'
Description: VPC with Internet Gateway

Parameters:
  VPCCidrBlock:
    Type: String
    Description: CIDR block for the VPC
  Environment:
    Type: String
    Description: Environment name
  TagName:
    Type: String
    Description: Value for tag Name
  TagRegion:
    Type: String
    Description: Value for tag Region
  ExportName:
    Type: String
    Description: Name to export

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidrBlock  # 10.127.0.0/20
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "ar-vpc-${TagName}"  # ar-vpc-nms-me-south-1
        - Key: Env
          Value: !Ref Environment
        - Key: Region
          Value: !Ref TagRegion
        - Key: Apps
          Value: NMS
        - Key: Owner
          Value: NSG Dev Team
        - Key: ITSM
          Value: ''
        - Key: CostCentre
          Value: ''

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "ar-igw-vpc-${TagName}"  # ar-igw-vpc-nms-me-south-1
        - Key: Env
          Value: !Ref Environment
        - Key: Region
          Value: !Ref TagRegion
        - Key: Apps
          Value: NMS
        - Key: Owner
          Value: NSG Dev Team
        - Key: ITSM
          Value: ''
        - Key: CostCentre
          Value: ''

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref InternetGateway

Outputs:
  VpcId:
    Value: !Ref MyVPC
    Export:
      Name: !Ref ExportName
