AWSTemplateFormatVersion: '2010-09-09'
Description: RDS MySQL instance

Parameters:
  PrivateSubnet1Id:
    Type: String
  PrivateSubnet2Id:
    Type: String

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS subnet group
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: mysql-subgroup-sub-pvt2-vpc-nms-dev-me-south-1a
        - Key: Env
          Value: dev
        - Key: Region
          Value: me-south-1a
        - Key: Apps
          Value: NMS
        - Key: Owner
          Value: Oreta Dev Team
        - Key: ITSM
          Value: ITSM-1234
        - Key: CostCentre
          Value: CC-1234

  MySQLRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: mysql-db-instance
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: MySecurePass123
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups: []  # Add security groups later
      PubliclyAccessible: false
      MultiAZ: false
      Tags:
        - Key: Name
          Value: mysql-sub-pvt2-vpc-nms-dev-me-south-1a
        - Key: Env
          Value: dev
        - Key: Region
          Value: me-south-1a
        - Key: Apps
          Value: NMS
        - Key: Owner
          Value: Oreta Dev Team
        - Key: ITSM
          Value: ITSM-1234
        - Key: CostCentre
          Value: CC-1234
