AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to create an S3 bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ar-unique-s3-bucket-name
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket
