AWSTemplateFormatVersion: '2010-09-09'
Description: Subnets inside VPC

Parameters:
  VpcId:
    Type: String
  AvailabilityZone:
    Type: String
  Environment:
    Type: String
    Description: Environment name
  TagRegion:
    Type: String
    Description: Value for tag Region
  PublicCidrBlock1:
    Type: String
    Description: CIDR block for public subnet 1
  PrivateCidrBlock1:
    Type: String
    Description: CIDR block for private subnet 1
  PrivateCidrBlock2:
    Type: String
    Description: CIDR block for private subnet 2
  PrivateCidrBlock3:
    Type: String
    Description: CIDR block for private subnet 3

Resources:
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref PublicCidrBlock1
      AvailabilityZone: !Ref AvailabilityZone
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "sub-pub1-vpc-nms-${Environment}-${TagRegion}"
        - Key: Env
          Value: !Ref Environment
        - Key: Region
          Value: !Ref Region
        - Key: Apps
          Value: NMS
        - Key: Owner
          Value: NSG Dev Team
        - Key: ITSM
          Value:
        - Key: CostCentre
          Value:

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref PrivateCidrBlock1
      AvailabilityZone: !Ref AvailabilityZone
      Tags:
        - Key: Name
          Value: !Sub "sub-pvt1-vpc-nms-${Environment}-${TagRegion}"
        - Key: Env
          Value: !Ref Environment
        - Key: Region
          Value: !Ref TagRegion
        - Key: Apps
          Value: NMS
        - Key: Owner
          Value: NSG Dev Team
        - Key: ITSM
          Value:
        - Key: CostCentre
          Value:

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref PrivateCidrBlock2
      AvailabilityZone: !Ref AvailabilityZone
      Tags:
        - Key: Name
          Value: !Sub "sub-pvt2-vpc-nms-${Environment}-${TagRegion}"
        - Key: Env
          Value: !Ref Environment
        - Key: Region
          Value: !Ref TagRegion
        - Key: Apps
          Value: NMS
        - Key: Owner
          Value: NSG Dev Team
        - Key: ITSM
          Value:
        - Key: CostCentre
          Value:

  PrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref PrivateCidrBlock3
      AvailabilityZone: !Ref AvailabilityZone
      Tags:
        - Key: Name
          Value: !Sub "sub-pvt3-vpc-nms-${Environment}-${TagRegion}"
        - Key: Env
          Value: !Ref Environment
        - Key: Region
          Value: !Ref TagRegion
        - Key: Apps
          Value: NMS
        - Key: Owner
          Value: NSG Dev Team
        - Key: ITSM
          Value:
        - Key: CostCentre
          Value:

Outputs:
  PublicSubnetId:
    Value: !Ref PublicSubnet1
  PrivateSubnet1Id:
    Value: !Ref PrivateSubnet1
  PrivateSubnet2Id:
    Value: !Ref PrivateSubnet2
  PrivateSubnet3Id:
    Value: !Ref PrivateSubnet3
  PrivateSubnetIds:
    Value: !Join [ ",", [ !Ref PrivateSubnet1, !Ref PrivateSubnet2, !Ref PrivateSubnet3 ]]
