name: Deploy to AWS CloudFormation

on:
  push:
    branches:
      - main # Trigger deployment on push to main branch
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  deploy:
    name: Deploy S3 Bucket with CloudFormation
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: me-south-1 # Change to your desired region

      - name: Deploy CloudFormation stack
        run: |
          # aws s3 mb s3://ar-nsg-cf-templates --region me-south-1
          aws s3 cp templates/vpc.yml s3://ar-nsg-cf-templates/
          aws s3 cp templates/subnet.yml s3://ar-nsg-cf-templates/
          aws s3 cp templates/ec2.yml s3://ar-nsg-cf-templates/
          aws cloudformation deploy \
            --template-file templates/main1.yml \
            --stack-name vpc-subnet-ec2-stack \
            --parameter-overrides TemplateBucket=ar-nsg-cf-templates \
            --capabilities CAPABILITY_NAMED_IAM
          # aws cloudformation delete-stack --stack-name my-s3-bucket-stack
