name: Deploy to AWS CloudFormation

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  deploy:
    name: Deploy S3 Bucket with CloudFormation
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    env:
      AWS_REGION: me-south-1 # Change to your desired region
      TEMPLATE_BUCKET: ar-nsg-cf-templates
      DEPLOY_DIR: infrastructure
      STACK_NAME: vpc-subnet-ec2-stack
      ENVIRONMENT: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create S3 bucket for Templates
        run: |
          aws s3 mb s3://${TEMPLATE_BUCKET} --region ${AWS_REGION} || true

      - name: Upload Templates to S3
        run: |
          aws s3 cp ${DEPLOY_DIR}/${ENVIRONMENT}/templates/vpc.yml s3://${TEMPLATE_BUCKET}/${DEPLOY_DIR}/${ENVIRONMENT}/
          aws s3 cp ${DEPLOY_DIR}/${ENVIRONMENT}/templates/subnet.yml s3://${TEMPLATE_BUCKET}/${DEPLOY_DIR}/${ENVIRONMENT}/
          aws s3 cp ${DEPLOY_DIR}/${ENVIRONMENT}/templates/ec2.yml s3://${TEMPLATE_BUCKET}/${DEPLOY_DIR}/${ENVIRONMENT}/

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file ${DEPLOY_DIR}/${ENVIRONMENT}/templates/main1.yml \
            --stack-name ${STACK_NAME}-${ENVIRONMENT} \
            --parameter-overrides TemplateBucket=${TEMPLATE_BUCKET} Env=${ENVIRONMENT} DeployDir=${DEPLOY_DIR} \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Show Stack Events
        if: always()
        run: |
          aws cloudformation describe-stack-events --stack-name ${STACK_NAME}-${ENVIRONMENT}
